### ISSUE TITLE
Duplicate section on page wiki/Configuration

### ISSUE THREAD

**Issue by ole** [ttscoff/searchlink#16]
I don't know if/how I can send a pull request for a wiki page, which is why I'm creating a simple issue for this.

On the [Configuration page](https://github.com/ttscoff/searchlink/wiki/Configuration), there's a duplicated section in the sample config file:

```yaml
# Formatting for social links, use %service%, %user%, and %url%
# E.g. "%user% on %service%" => "ttscoff on Twitter"
#      "%service%/%user%" => "Twitter/ttscoff"
#      "%url%" => "twitter.com/ttscoff"
social_template: "%service%/%user%"

…

# Formatting for social links, use %service%, %user%, and
# %url%
# E.g. "%user% on %service%" => "ttscoff on Twitter"
# "%service%/%user%" => "Twitter/ttscoff"
# "%url%" => "twitter.com/ttscoff"
social_template: "@%user% on %service%"
```

One of these should be removed.
